### ISSUE TITLE
Wifi driver for joystick

### ISSUE THREAD

**Issue by mkeyno** [RespawnDespair/wifibroadcast-rc#1]
hi , sorry to open a ticket for my question, but I have some questions that your probably advise is really appreciated
Actually I've been trying to send some game keys, base on HID protocol to the computer by wifi link(ESP8266). PC computer with OS like Microsoft Windows instantly make "HID-compliant game controller" driver with typical USB joystick , my question is, how make specific driver which is shows up same as "HID-compliant game controller" but listen to specific IP address instead of USB
tnx

**Comment by RespawnDespair** [comment]
This is really out of scope for this repository.
But here's my 2 cents anyway.

Assuming you want to connect a USB joystick, you'd need a board to connect the usb joystick to the ESP8266. Then you'd need to read the axis/buttons and send them trough wifi to another ESP8266 which is connected to the host pc. There you'd use the USB HID library to have the ESP show up as a generic HID gaming device and you'd update using the stream recieved over Wifi.

Some quick search gives you this:
https://github.com/gdsports/esp8266-usb-host-demos

Which essentially does this, but for a keyboard device.

Because this question is so far out of scope for this repository, i'm closing the issue. Hopefully the link will get you underway with your project.
